### ISSUE TITLE
request for use

### ISSUE THREAD

**Issue by xtr3m598** [Scarso327/PhoenixRP-Altis-Mission#6] opened 2021-11-25 15:32 UTC
Hello, excuse me for disturbing you. I am French and I come to you because I would like to know if I can use your mission to use it as a basis on which I will add content. My goal is not to appropriate your work on the contrary. I have studied your framework at length and I appreciate your work which is why I would like to use it to work on it and then make it a public game server. I would only do it if you allowed me to do so. Thanks in advance.

**Comment by Scarso327** [comment] 2021-11-25 15:59
Do whatever you want

**Comment by xtr3m598** [comment] 2021-11-26 10:18
Are you sure? I wouldn't have any copyright concerns or even a problem with the license ?

I also have a few questions for you if that is possible. Thanks in advance.

**Comment by Scarso327** [comment] 2021-11-26 10:20
Unsure how I can help but if you have any questions I'll answer them to the best of my ability.

No copyright concerns. This is public for a reason.

**Comment by xtr3m598** [comment] 2021-11-26 14:47
Okay thanks.

So first of all I wanted to know if it was possible to display the price in the stock market because for the moment it is displayed -1 so it's a little annoying. After I know that the scholarship was not over. I also wanted to know how the selling price of an item is calculated.

Then I noticed that the achievements section did not work. When you have to unlock an achievements nothing happens and nothing is listed in the menu is this normal?

In the switch that is present in the file fn_drink the last box does not work it does not execute the overdose script I tried something but its did nothing, after we could replace it with an if as in the fn_drug that executes the script well but it is less top.

Thanks in advance.

**Comment by Scarso327** [comment] 2021-11-26 16:19
Sell Prices is likely due to missing data in the settings table. I can't remember exactly what was needed but it was used in the calculations. All virtual item prices are calculated in: https://github.com/Scarso327/PhoenixRP-Altis-Mission/blob/main/PhoenixRP.Altis/PHX/Functions/fn_calSellPrice.sqf

Achievements, what exactly is broken? This system worked perfectly last this mission was used.

I've pushed a fix. The order of the switch statement made the last option impossible to reach.

**Comment by xtr3m598** [comment] 2021-11-26 16:36
Thank you very much for the fix.

For Achievements it's strange but the whole system does not work I have nothing in database and no display in games when I succeed in a Achievements.

Thank you for the market system. I will try to look at its because the whole system works there is just the recovery of the selling price on the market menu that does not work.

**Comment by xtr3m598** [comment] 2021-11-28 16:43
Good evening, I also noticed that it is impossible to talk to other players no sound is emitted without knowing why.

The fn_breathalyse does not work it only displays the notification in the following and does not take into account the condition.

Thanks in advance.

**Comment by Scarso327** [comment] 2021-11-28 17:24
Talking to players is Arma. You'll have to fix bugs yourself. I'll help with major issues but I have a full time job doing Software Engineering and my personal projects.

**Comment by xtr3m598** [comment] 2021-11-29 13:48
Hello, yes I understand sorry for the inconvenience, thank you for the answers.

**Comment by Scarso327** [comment] 2022-02-09 18:17
https://github.com/Scarso327/PhoenixRP-Altis-Mission/commit/2d921b389f5eb4ea08d708f2f3afacc6ac0df2bf

Fix for the market. Inactive so assuming the issue is resolved.

**Closed by Scarso327** 2022-02-09 18:17 UTC
